# identifiant du projet créé sur SonarQube Cloud
sonar.projectKey=inesenrq29_ressource-relationnelle-front

# organisation SonarQube Cloud
sonar.organization=inesenrq29

# dossier contenant le code Angular
sonar.sources=src
sonar.tests=src

# encodage des fichiers
sonar.sourceEncoding=UTF-8

# on ignore la couverture de code sur TOUT le projet front pour ne pas impacter la Quality Gate
sonar.coverage.exclusions=**/*

# fichiers et dossiers complètement exclus de l'analyse générale
sonar.exclusions=**/*.spec.ts, **/node_modules/**, **/dist/**, **/coverage/**

# identification stricte des fichiers de tests
sonar.test.inclusions=**/*.spec.ts
