# identifiant du projet créé sur SonarQube Cloud
sonar.projectKey=inesenrq29_ressource-relationnelle-front

# organisation SonarQube Cloud
sonar.organization=inesenrq29

# dossier contenant le code Angular
sonar.sources=src

# encodage des fichiers
sonar.sourceEncoding=UTF-8

# fichiers et dossiers non analysés
sonar.exclusions=**/*.spec.ts,dist/**,node_modules/**